# Generated by Django 4.0.4 on 2022-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pile',
            name='pile_type',
            field=models.IntegerField(choices=[(0, 'Charge'), (1, 'Fast Charge')], default=0),
            preserve_default=False,
        ),
    ]
