# Generated by Django 4.0.4 on 2022-06-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('pile_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Running'), (1, 'Shutdown'), (2, 'Unavailable')])),
                ('cumulative_usage_times', models.IntegerField(default=0)),
                ('cumulative_charging_time', models.IntegerField(default=0)),
                ('cumulative_charging_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('create_time', models.DateTimeField()),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('charging_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charged_time', models.IntegerField()),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accs_app.pile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accs_app.user')),
            ],
        ),
    ]
